package constants;

public enum Commands {
    NETWORK_ANSWER,
    GET_FILE_LIST,
    GET_FILE_SHAREDLIST,
    GET_USERS_LIST,
    GET_FRIENDS_LIST,
    GET_MY_USERSHARES_LIST,
    GO_INTO_SHARED_MODE,
    GO_INTO_NORMAL_MODE,
    AUTHORISATION,
    SHARE_FOLDER,
    FILE_DATA,
    FILE_OVERWRITE,
    CREATE_NEW_FOLDER,
    DELETE,
    FILE_DOWNLOAD;

}
